<a href="https://colab.research.google.com/github/Ygarkakoito/neuron/blob/main/%D0%B2%D1%82%D0%BE%D1%80%D0%B0%D1%8F_%D0%BB%D0%B0%D0%B1%D0%B0_%D0%B5%D0%B3%D0%BE%D1%80%D0%BE%D0%B2%D0%B0v1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import torch


## 2.1 Создание нейронов и полносвязных слоев

2.1.1. Используя операции над матрицами и векторами из библиотеки `torch`, реализовать нейрон с заданными весами `weights` и `bias`. Прогнать вектор `inputs` через нейрон и вывести результат.

In [5]:
import torch

class Neuron:
    def __init__(self, weights, bias):
        # Инициализация весов и смещения
        self.weights = weights
        self.bias = bias

    def forward(self, inputs):
        # Вычисление выхода нейрона (взвешенная сумма входов + смещение)
        output = torch.dot(self.weights, inputs) + self.bias
        return output



In [6]:
inputs = torch.tensor([1.0, 2.0, 3.0, 4.0])
# Заданные веса
weights = torch.tensor([-0.2, 0.3, -0.5, 0.7])
#смещение
bias = 3.14
#нейрон с заданными параметрами
neuron = Neuron(weights, bias)
#входные данные через нейрон
output = neuron.forward(inputs)
print( output)

tensor(4.8400)


2.1.2 Используя операции над матрицами и векторами из библиотеки `torch`, реализовать полносвязный слой с заданными весами `weights` и `biases`. Прогнать вектор `inputs` через слой и вывести результат.

In [7]:
class Linear:
    def __init__(self, weights, biases):
        # Инициализация весов и смещений
        self.weights = weights
        self.biases = biases

    def forward(self, inputs):
        # выход слоя после применения взвешенной суммы входныщ данных и добавления смещений.
        output = torch.matmul(inputs, self.weights) + self.biases #matmul - матричное умножение между двумя тензорами
        return output


In [8]:
inputs = torch.tensor([1.0, 2.0, 3.0, 4.0])
#  веса (транспонированные, чтобы соответствовать матричному умножению) и смещения
weights = torch.tensor([[-0.2, 0.3, -0.5, 0.7],
                        [0.5, -0.91, 0.26, -0.5],
                        [-0.26, -0.27, 0.17, 0.87]]).T    #.T -  в библиотеке PyTorch транспонирование матрицы.
biases = torch.tensor([3.14, 2.71, 7.2])

# Создаем полносвязный слой с заданными параметрами
layer = Linear(weights, biases)

# Прогоняем входные данные через слой
output = layer.forward(inputs)
print( output)

tensor([ 4.8400,  0.1700, 10.3900])


2.1.3 Реализовать полносвязный слой из __2.1.2__ таким образом, чтобы он мог принимать на вход матрицу (батч) с данными. Продемонстрировать работу.
Результатом прогона сквозь слой должна быть матрица размера `batch_size` x `n_neurons`.


In [9]:
class LinearLayer:
    def __init__(self, input_size, output_size):
        # Инициализация весов и смещений случайными значениями
        self.weights = torch.randn(input_size, output_size)
        self.biases = torch.zeros(1, output_size)  #torch.zeros - создает тензор заполненный нулями.

    def forward(self, inputs):
        # Вычисление выхода слоя
        output = torch.matmul(inputs, self.weights) + self.biases
        return output

inputs = torch.tensor([[1, 2, 3, 2.5],
                       [2, 5, -1, 2],
                       [-1.5, 2.7, 3.3, -0.8]])

# Создаем полносвязный слой с заданными размерами
batch_size = inputs.shape[0]   # inputs.shape[1] -  размерность Матрицы
input_size = inputs.shape[1]   # число признаков
output_size = 3               # Число нейронов
# Создаем полносвязный слой с заданными размерами
layer = LinearLayer(input_size, output_size)

# Прогоняем входные данные через слой
output = layer.forward(inputs)
print(output)


tensor([[-2.6427, -1.2913,  9.9646],
        [ 2.7228, -2.8230,  7.9035],
        [-9.4826,  1.6502,  3.3985]])


2.1.4 Используя операции над матрицами и векторами из библиотеки `torch`, реализовать полносвязный слой из `n_neurons` нейронов с `n_features` весами у каждого нейрона (инициализируются из стандартного нормального распределения). Прогнать вектор `inputs` через слой и вывести результат. Результатом прогона сквозь слой должна быть матрица размера `batch_size` x `n_neurons`.

In [10]:
import random

class Linear:
    def __init__(self, n_features, n_neurons):
        # Инициализация весов из стандартного нормального распределения и смещений нулями
        self.weights = torch.randn(n_features, n_neurons)
        self.biases = torch.zeros(1, n_neurons)#создается тензор размером (1, n_neurons), где 1 количество строк и n_neurons - количество нейронов в слое. Таким образом, для каждого нейрона у нас есть одно смещение.

    def forward(self, inputs):
        # Вычисление выхода слоя
        output = torch.matmul(inputs, self.weights) + self.biases
        return output

inputs = torch.tensor([[1, 2, 3, 2.5],
                       [2, 5, -1, 2],
                       [-1.5, 2.7, 3.3, -0.8]])

# Получаем размеры входных данных (batch_size)
batch_size, n_features = inputs.shape
n_neurons = random.randint(1, 10)
# Создаем полносвязный слой с заданными параметрами
layer = Linear(n_features, n_neurons)
# Прогоняем входные данные через слой
output = layer.forward(inputs)
print(output)


tensor([[ 1.6763, -2.3353, -1.3512,  0.4950, -4.2232, -7.9134, -0.1491, -1.3697,
         -0.0851],
        [ 0.6528,  2.4480, -6.9328, -3.5239,  5.5778,  1.1055,  0.6546,  6.2809,
         -1.3707],
        [ 9.2531,  0.1709, -2.2112, -0.1650, -5.9738, -4.8129,  5.2242,  0.3557,
          0.1102]])


2.1.5 Используя решение из __2.1.4__, создать 2 полносвязных слоя и пропустить матрицу `inputs` последовательно через эти два слоя. Количество нейронов в первом слое выбрать произвольно, количество нейронов во втором слое выбрать так, чтобы результатом прогона являлась матрица (3x7).

In [11]:
class Linear:
    def __init__(self, input_size, output_size):
        # Инициализация весов из стандартного нормального распределения и смещений нулями
        self.weights = torch.randn(input_size, output_size)
        self.biases = torch.zeros(1, output_size)

    def forward(self, inputs):
        # Вычисление выхода слоя
        output = torch.matmul(inputs, self.weights) + self.biases
        return output

inputs = torch.tensor([[1, 2, 3, 2.5],
                       [2, 5, -1, 2],
                       [-1.5, 2.7, 3.3, -0.8]])

# Получаем размеры данных (batch_size)
batch_size, input_size = inputs.shape
# Задаем произвольное количество нейронов в первом слое
n_neurons_1 = random.randint(1, 10)
n_neurons_2 = 7

# Создаем два полносвязных слоя
layer1 = Linear(input_size, n_neurons_1)
layer2 = Linear(n_neurons_1, n_neurons_2)

# Прогоняем входные данные через слоя
output1 = layer1.forward(inputs)
output2 = layer2.forward(output1)

print(output1,output2)

tensor([[ -1.1048,  -4.0769,  -4.7125,  -1.0234,  -0.5207,   1.1904,   0.5682],
        [ -6.3920, -10.0574,  -2.2585,   5.5514,   3.8663,  -1.6230,   3.4153],
        [  2.5446,  -2.8737,  -4.8097,   4.3865,  -1.1289,   8.7595,   8.9266]]) tensor([[ -2.2888,  -8.1606,  -1.5393,   4.4760,   3.5239,  -3.8310,  10.7168],
        [ -6.6715,  -0.6912, -19.8736, -24.0452,   5.5523, -13.7955,  43.2604],
        [ -2.0772, -22.9993,   3.1319,   0.5813,  10.6662,  10.5072,   6.8514]])


## 2.2 Создание функций активации

2.2.1 Используя операции над матрицами и векторами из библиотеки `torch`, реализовать функцию активации ReLU:

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/f4353f4e3e484130504049599d2e7b040793e1eb)

Создать матрицу размера (4,3), заполненную числами из стандартного нормального распределения, и проверить работоспособность функции активации.

In [12]:
import numpy as np

class ReLU:
    def forward(self, inputs):
        result = torch.where(inputs > 0, inputs, torch.tensor(0.0)) # ReLU заменяет отрицательные значения на нули, оставляя положительные значения без изменений. (where просто условная оперция типа того)
        return result

matrix = torch.randn(4, 3)
relu = ReLU()
output = relu.forward(matrix)

print("Исходная матрица:",matrix)
print("Результат после применения ReLU:",output)


Исходная матрица: tensor([[ 1.6418, -0.5919, -0.7107],
        [ 0.8002,  0.2380, -0.2935],
        [-0.9242,  0.2684,  0.5580],
        [ 0.9941,  1.1855,  0.2210]])
Результат после применения ReLU: tensor([[1.6418, 0.0000, 0.0000],
        [0.8002, 0.2380, 0.0000],
        [0.0000, 0.2684, 0.5580],
        [0.9941, 1.1855, 0.2210]])


2.2.2 Используя операции над матрицами и векторами из библиотеки `torch`, реализовать функцию активации softmax:

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/6d7500d980c313da83e4117da701bf7c8f1982f5)

Создать матрицу размера (4,3), заполненную числами из стандартного нормального распределения, и проверить работоспособность функции активации. Строки матрицы трактовать как выходы линейного слоя некоторого классификатора для 4 различных примеров.

In [13]:
class Softmax:
  def forward(self, x):
    res = torch.exp(x)/(torch.exp(x).sum())
    return res


In [14]:
nn = torch.nn.Softmax(dim=1)
nn.forward(inputs)

tensor([[0.0641, 0.1744, 0.4740, 0.2875],
        [0.0452, 0.9074, 0.0022, 0.0452],
        [0.0052, 0.3488, 0.6355, 0.0105]])

In [15]:
inputs = torch.tensor([[1, 2, 3, 2.5],
                       [2, 5, -1, 2],
                       [-1.5, 2.7, 3.3, -0.8]])
ss=Softmax()
ss.forward(inputs)

tensor([[0.0109, 0.0297, 0.0808, 0.0490],
        [0.0297, 0.5970, 0.0015, 0.0297],
        [0.0009, 0.0599, 0.1091, 0.0018]])

2.2.3 Используя операции над матрицами и векторами из библиотеки `torch`, реализовать функцию активации ELU:

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/eb23becd37c3602c4838e53f532163279192e4fd)

Создать матрицу размера (4,3), заполненную числами из стандартного нормального распределения, и проверить работоспособность функции активации.

In [16]:
class ELU:
    def __init__(self, alpha):
        self.alpha = alpha

    def forward(self, inputs):

        result = torch.where(inputs >= 0, inputs, self.alpha * (torch.exp(inputs) - 1)) #заменяем отрицательные значения в inputs на значения, вычисленные с помощью функции активации ELU (a * (e^x - 1)), где a - параметр alpha. Если значение положительное или ноль, то оно остается без изменений.
        return result

matrix = torch.randn(4, 3)
elu = ELU(alpha=1.0)
output = elu.forward(matrix)
print("Исходная матрица:",matrix)
print("Результат после применения ELU:",output)


Исходная матрица: tensor([[ 0.8634,  0.9338, -0.5790],
        [-0.1234,  0.6972, -0.1750],
        [ 0.4908, -0.8319, -0.9447],
        [ 1.1324,  0.4761,  0.0046]])
Результат после применения ELU: tensor([[ 0.8634,  0.9338, -0.4396],
        [-0.1161,  0.6972, -0.1606],
        [ 0.4908, -0.5648, -0.6112],
        [ 1.1324,  0.4761,  0.0046]])


## 2.3 Создание функции потерь

2.3.1 Используя операции над матрицами и векторами из библиотеки `torch`, реализовать функцию потерь MSE:

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/e258221518869aa1c6561bb75b99476c4734108e)

Создать полносвязный слой с 1 нейроном, прогнать через него батч `inputs` и посчитать значение MSE, трактуя вектор `y` как вектор правильных ответов.

In [17]:
class Linear:
    def __init__(self, input_size, output_size):
        self.weights = torch.randn(input_size, output_size)
        self.biases = torch.zeros(1, output_size)

    def forward(self, inputs):
        output = torch.matmul(inputs, self.weights) + self.biases
        return output

class MSELoss:
    def forward(self, y_pred, y_true):
        mse = torch.mean((y_pred - y_true) ** 2)
        return mse

inputs = torch.tensor([[1, 2, 3, 2.5],
                       [2, 5, -1, 2],
                       [-1.5, 2.7, 3.3, -0.8]])

# Истинные значения
y_true = torch.tensor([2, 3, 4]).reshape(-1, 1)  # вектор в матрицу 3, 1

# Создаем полносвязный слой с 1 нейроном
input_size = inputs.shape[1]  #число признаков
output_size = 1  # Один нейрон для регрессии
layer = Linear(input_size, output_size)
y_pred = layer.forward(inputs)
mse_loss = MSELoss()
loss = mse_loss.forward(y_pred, y_true)

print("Предсказанные значения:",y_pred,"Истинные значения:",y_true,"Значение MSE:",loss)


Предсказанные значения: tensor([[-0.0984],
        [ 4.0748],
        [ 4.0577]]) Истинные значения: tensor([[2],
        [3],
        [4]]) Значение MSE: tensor(1.8539)


2.3.2 Используя операции над матрицами и векторами из библиотеки `torch`, реализовать функцию потерь Categorical Cross-Entropy:

<img src="https://i.ibb.co/93gy1dN/Screenshot-9.png" width="200">

Создать полносвязный слой с 3 нейронами и прогнать через него батч `inputs`. Полученный результат пропустить через функцию активации softmax. Посчитать значение CCE, трактуя вектор `y` как вектор правильных ответов.

In [18]:
class CategoricalCrossentropyLoss:
    def forward(self, y_pred, y_true):
        cce = -torch.sum(y_true * torch.log(y_pred))
        return cce

class Softmax:
    def forward(self, x):
        # Применение функции активации Softmax
        result = torch.exp(x - torch.max(x, dim=1, keepdim=True).values)
        result /= torch.sum(result, dim=1, keepdim=True)  #keepdim=True  -контролирует, будут ли сохранены или уменьшены размерности тензора после выполнения операции (то есть размерность будет dim=1).
        return result

inputs = torch.tensor([[1, 2, 3, 2.5],
                       [2, 5, -1, 2],
                       [-1.5, 2.7, 3.3, -0.8]])

y_true = torch.tensor([[1, 0, 0],
                       [0, 1, 0],
                       [0, 0, 1]])

input_size = inputs.shape[1]
output_size = 3
layer = Linear(input_size, output_size)
y_pred = layer.forward(inputs)
softmax = Softmax()
y_pred_softmax = softmax.forward(y_pred)
cce_loss = CategoricalCrossentropyLoss()
loss = cce_loss.forward(y_pred_softmax, y_true)

print("Предсказанные значения (Softmax):")
print(y_pred_softmax)
print("Истинные значения:")
print(y_true)
print("Значение Categorical Cross-Entropy Loss:")
print(loss)

Предсказанные значения (Softmax):
tensor([[2.0851e-06, 9.7232e-01, 2.7673e-02],
        [7.4069e-03, 4.2856e-03, 9.8831e-01],
        [3.7651e-06, 9.9999e-01, 1.1010e-05]])
Истинные значения:
tensor([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]])
Значение Categorical Cross-Entropy Loss:
tensor(29.9499)


2.3.3 Модифицировать 2.3.1, добавив L2-регуляризацию.

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/d92ca2429275bfdc0474523babbafe014ca8b580)


In [19]:
class MSELossL2:
    def __init__(self, lambda_):
        self.lambda_ = lambda_

    def data_loss(self, y_pred, y_true):
        # Вычисление потери данных (MSE)
        mse = torch.mean((y_pred - y_true) ** 2)
        return mse

    def reg_loss(self, layer):
        # Вычисление регуляризационной потери L2
        l2_loss = torch.sum(layer.weights ** 2) * self.lambda_  # L2-регуляризация
        return l2_loss

    def forward(self, y_pred, y_true, layer):
        # Общая потеря как сумма потери данных и регуляризационной потери
        total_loss = self.data_loss(y_pred, y_true) + self.reg_loss(layer)
        return total_loss


input_size = inputs.shape[1]
output_size = 1
layer = Linear(input_size, output_size)
y_pred = layer.forward(inputs)

# MSELossL2 с параметром lambda_=0.01
lambda_ = 0.01
mse_loss_l2 = MSELossL2(lambda_)

#общая потеря с учетом L2-регуляризации
total_loss = mse_loss_l2.forward(y_pred, y_true, layer)

print("Предсказанные значения:", y_pred)
print("Истинные значения:", y_true)
print("Значение MSELoss с L2-регуляризацией:", total_loss)


Предсказанные значения: tensor([[-6.4279],
        [-6.5120],
        [-5.7902]])
Истинные значения: tensor([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]])
Значение MSELoss с L2-регуляризацией: tensor(43.6073)


## 2.4 Обратное распространение ошибки

2.4.1 Используя один нейрон и SGD (1 пример за шаг), решите задачу регрессии

In [20]:
from sklearn.datasets import make_regression
X, y, coef = make_regression(n_features=4, n_informative=4, coef=True, bias=0.5)  #n_features: Это параметр, который указывает количество признаков (факторов), которые будут участвовать в созданных данных
#n_informative: Это параметр, который указывает количество информативных признаков, которые действительно влияют на целевую величину, которую мы пытаемся предсказать
X = torch.from_numpy(X).to(torch.float32) #преобразует массив X в тензор
y = torch.from_numpy(y).to(torch.float32)

In [21]:
coef

array([65.80849942, 69.58911489, 48.32251677, 15.31132061])

[Граф вычислений для этой задачи](https://i.ibb.co/2dhDxZx/photo-2021-02-15-17-18-04.jpg)

2.4.1.1 Реализуйте класс `SquaredLoss`


In [22]:
class SquaredLoss:
  def forward(self, y_pred, y_true):
    #E = torch.square(y_pred - y_true).mean()
    E =((y_pred-y_true)**2).mean()
    return E # <реализовать логику MSE>

  def backward(self, y_pred, y_true):
    self.dinput = 2*(y_pred-y_true) #-(2/y_pred.size()[0])*[(y_pred-y_true)] # df/dc #dinput-градиент функции потерь

y_pred = torch.tensor([2,3,4])
y_t = torch.tensor([2,3,4.5])
sql=SquaredLoss()
sql.forward(y_pred,y_t)

tensor(0.0833)

2.4.1.2. Модифицируйте класс `Neuron` из __2.1.1__:

  1) Сделайте так, чтобы веса нейрона инициализировались из стандартного нормального распределения

  2) Реализуйте расчет градиента относительно весов `weights` и `bias`

In [23]:
class Neuron:
  def __init__(self, n_inputs):
    self.w=torch.randn(n_inputs)
    self.b=torch.randn(1)
    pass

  def forward(self, inputs):
    self.inputs=inputs
    return torch.dot(inputs,self.w)+self.b #Вычисляет взвешенную сумму входных данных и весов нейрона, затем добавляет смещение
    #torch.dot(inputs, self.w): вычисляет скалярное произведение между вектором входных данных inputs и вектором весов нейрона self.w

  def backward(self, dvalue):
    # dvalue - значение производной, которое приходит нейрону от следующего слоя сети
    # в данном случае это будет значение df/dc (созданное методом backwards у объекта MSELoss)
    self.dweights = self.inputs*dvalue  #dweights- градиент (производная) потери по отношению к весам (weights) нейрона
    self.dinput =  self.w*dvalue  #dinput-градиент функции потерь
    self.dbias =dvalue


2.4.1.3 Допишите цикл для настройки весов нейрона

[SGD](https://ru.wikipedia.org/wiki/%D0%A1%D1%82%D0%BE%D1%85%D0%B0%D1%81%D1%82%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B9_%D0%B3%D1%80%D0%B0%D0%B4%D0%B8%D0%B5%D0%BD%D1%82%D0%BD%D1%8B%D0%B9_%D1%81%D0%BF%D1%83%D1%81%D0%BA)

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/dda3670f8a8996a0d3bf80856bb4a166cc8db6d4)

In [24]:
n_inputs = X.size()[1] #Определяет количество входных признаков (нейронов) на основе размерности матрицы X.
lr = 0.1 #  скорость обучения
n_epoch = 100 #  количество эпох

neuron = Neuron(n_inputs)
loss = SquaredLoss()

In [25]:
losses = []
for epoch in range(100):
  print(neuron.w)
  for x_example, y_example in zip(X, y): #zip(X, y) - объединяет два объекта X и y попарно
    y_pred = neuron.forward(x_example)
    curr_loss = loss.forward(y_pred,y_example)
    losses.append(curr_loss)

    loss.backward(y_pred,y_example)
    neuron.backward(loss.dinput) #dinput-градиент функции потерь

    neuron.w-=lr*neuron.dweights
    neuron.b-=lr*neuron.dbias

tensor([-0.7654, -1.0248, -0.6929,  0.5084])
tensor([65.8071, 69.5808, 48.3187, 15.3064])
tensor([65.8085, 69.5891, 48.3225, 15.3113])
tensor([65.8085, 69.5891, 48.3225, 15.3113])
tensor([65.8085, 69.5891, 48.3225, 15.3113])
tensor([65.8085, 69.5891, 48.3225, 15.3113])
tensor([65.8085, 69.5891, 48.3225, 15.3113])
tensor([65.8085, 69.5891, 48.3225, 15.3113])
tensor([65.8085, 69.5891, 48.3225, 15.3113])
tensor([65.8085, 69.5891, 48.3225, 15.3113])
tensor([65.8085, 69.5891, 48.3225, 15.3113])
tensor([65.8085, 69.5891, 48.3225, 15.3113])
tensor([65.8085, 69.5891, 48.3225, 15.3113])
tensor([65.8085, 69.5891, 48.3225, 15.3113])
tensor([65.8085, 69.5891, 48.3225, 15.3113])
tensor([65.8085, 69.5891, 48.3225, 15.3113])
tensor([65.8085, 69.5891, 48.3225, 15.3113])
tensor([65.8085, 69.5891, 48.3225, 15.3113])
tensor([65.8085, 69.5891, 48.3225, 15.3113])
tensor([65.8085, 69.5891, 48.3225, 15.3113])
tensor([65.8085, 69.5891, 48.3225, 15.3113])
tensor([65.8085, 69.5891, 48.3225, 15.3113])
tensor([65

In [26]:
coef

array([65.80849942, 69.58911489, 48.32251677, 15.31132061])

In [27]:
neuron.w

tensor([65.8085, 69.5891, 48.3225, 15.3113])

2.4.1.1 Модифицируйте класс `MSELoss` из __2.3.1__, реализовав расчет производной относительно предыдущего слоя с учетом того, что теперь работа ведется с батчами, а не с индивидуальными примерами


In [28]:
class MSELoss:
    def forward(self, y_pred, y_true):
        # Рассчитываем MSE
        self.diff = y_pred - y_true
        mse = torch.mean(self.diff ** 2) #torch.mean - среднее значение всех элементов в тензоре
        return mse

    def backward(self):
        # Рассчитываем производную относительно y_pred (df/dy^)
        num_samples = self.diff.size(0)
        self.dinput = 2 * self.diff / num_samples  # Усредняем по батчу (ев запомни уже, что батча это группа обучающих примеров,которые обрабатываются одновременно моделью.)

mse_loss = MSELoss()

loss = mse_loss.forward(y_pred, y_true)
print("Значение MSE Loss:", loss)

mse_loss.backward()
print("Градиент df/dy^:",mse_loss.dinput)




Значение MSE Loss: tensor(32202.0098)
Градиент df/dy^: tensor([[-120.0768, -119.4102, -119.4102],
        [-119.4102, -120.0768, -119.4102],
        [-119.4102, -119.4102, -120.0768]])


2.4.2.2. Модифицируйте класс `Neuron` из __2.4.1.2__:

  1) Реализуйте метод `forward` таким образом, чтобы он мог принимать на вход матрицу (батч) с данными.

  2) Реализуйте расчет градиента относительно весов `weights` и `bias` с учетом того, что теперь работа ведется с батчами, а не с индивидуальными примерами

In [29]:
class Neuron:
    def __init__(self, n_inputs):
        # Инициализируем веса и смещение случайными значениями
        self.weights = torch.randn(n_inputs)
        self.bias = torch.randn(1)

    def forward(self, inputs):
        # Производим прямой проход через нейрон для батча
        self.inputs = inputs
        return torch.matmul(inputs, self.weights) + self.bias

    def backward(self, dvalue):
        # Рассчитываем градиенты для весов и смещения с учетом батча
        self.dweights = torch.matmul(self.inputs.T, dvalue)  # df/dW
        self.dbias = torch.sum(dvalue, dim=0, keepdim=True)  # df/db


In [30]:
n_inputs = 4
neuron = Neuron(n_inputs)

batch_size = 3
inputs = torch.tensor([[1.0, 2.0, 3.0, 2.5],
                       [2.0, 5.0, -1.0, 2.0],
                       [-1.5, 2.7, 3.3, -0.8]])

# Производим прямой проход через нейрон для батча данных
outputs = neuron.forward(inputs)

print("Выходы нейрона для батча данных:")
print(outputs)

# Рассчитываем градиенты для батча
dvalue = torch.randn(batch_size, 1)
# Производим обратный проход и расчет градиентов для батча
neuron.backward(dvalue)


print("Градиенты для весов (dweights):")
print(neuron.dweights)
print("Градиент для смещения (dbias):")
print(neuron.dbias)

Выходы нейрона для батча данных:
tensor([-8.5923, -3.5978, -5.8612])
Градиенты для весов (dweights):
tensor([[ 0.5954],
        [-8.3179],
        [-7.7524],
        [-1.9727]])
Градиент для смещения (dbias):
tensor([[-2.9780]])


2.4.2.3 Допишите цикл для настройки весов нейрона

In [31]:
class Neuron:
    def __init__(self, n_inputs):
        self.weights = torch.randn(n_inputs)
        self.bias = torch.randn(1)
        self.dweights = torch.zeros_like(self.weights)
        self.dbias = torch.zeros_like(self.bias)

    def forward(self, inputs):
        self.inputs = inputs
        return torch.matmul(inputs, self.weights) + self.bias

    def backward(self, dvalue):
        self.dweights = torch.matmul(self.inputs.T, dvalue)  # df/dW
        self.dbias = torch.sum(dvalue, dim=0, keepdim=True)  # df/db


n_inputs = inputs.size(1)  # Размерность элемента выборки
learning_rate = 0.1  # Скорость обучения
n_epoch = 100  # Количество эпох

inputs = torch.tensor([[1.0, 2.0, 3.0, 2.5],
                       [2.0, 5.0, -1.0, 2.0],
                       [-1.5, 2.7, 3.3, -0.8]])

neuron = Neuron(n_inputs)
loss = MSELoss()
losses = []

for epoch in range(n_epoch):
    # Forward pass
    y_pred = neuron.forward(inputs)
    curr_loss = loss.forward(y_pred, y_true)
    losses.append(curr_loss.item())  # Сохраняем текущее значение потери в списке

    # Backpropagation
    loss.backward()  # Рассчитываем градиенты относительно y_pred

    # Обновляем веса нейрона с учетом градиентов и скорости обучения
    neuron.weights -= learning_rate * neuron.dweights
    neuron.bias -= learning_rate * neuron.dbias

    if epoch % 10 == 0:
        print(f"Эпоха {epoch}: MSE Loss = {curr_loss.item()}")

print("Окончательные веса нейрона:", neuron.weights)
print("Окончательное смещение нейрона:", neuron.bias)


Эпоха 0: MSE Loss = 11.987822532653809
Эпоха 10: MSE Loss = 11.987822532653809
Эпоха 20: MSE Loss = 11.987822532653809
Эпоха 30: MSE Loss = 11.987822532653809
Эпоха 40: MSE Loss = 11.987822532653809
Эпоха 50: MSE Loss = 11.987822532653809
Эпоха 60: MSE Loss = 11.987822532653809
Эпоха 70: MSE Loss = 11.987822532653809
Эпоха 80: MSE Loss = 11.987822532653809
Эпоха 90: MSE Loss = 11.987822532653809
Окончательные веса нейрона: tensor([-0.1883, -1.0610,  0.5478,  0.4748])
Окончательное смещение нейрона: tensor([-0.1088])


2.4.3  Используя один полносвязный слой и  пакетный градиетный спуск, решите задачу регрессии из __2.4.1__

In [ ]:
from sklearn.datasets import make_regression
from sklearn.model_selection import train_test_split
import torch.nn as nn
import torch.optim as optim

X, y, coef = make_regression(n_features=4, n_informative=4, coef=True, bias=0.5)
X = torch.from_numpy(X).to(torch.float32)
y = torch.from_numpy(y).to(torch.float32)

# Разделяем данные на обучающий и тестовый наборы
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Определяем архитектуру нейронной сети
class RegressionModel(nn.Module):
    def __init__(self, input_size):
        super(RegressionModel, self).__init__()
        self.fc = nn.Linear(input_size, 1)  # создает полносвязный слой, который принимает на вход 4 признака(n_features=4, n_informative=4, coef=True, bias=0.5) и имеет один выходной нейрон

    def forward(self, x):
        return self.fc(x)

# Создаем модель и определяем функцию потерь и оптимизатор
input_size = X_train.shape[1]  # Размерность входных данных
model = RegressionModel(input_size)
criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.01)  # Оптимизатор SGD с заданной скоростью обучения

# Обучаем модель с использованием пакетного градиентного спуска
num_epochs = 100
batch_size = 32

for epoch in range(num_epochs):
    # Разбиваем данные на пакеты
    for i in range(0, len(X_train), batch_size):
        batch_X = X_train[i:i+batch_size]
        batch_y = y_train[i:i+batch_size]

        # Обнуляем градиенты
        optimizer.zero_grad()

        # Прямой проход
        outputs = model(batch_X)

        # Рассчитываем функцию потерь
        loss = criterion(outputs, batch_y)

        # Обратный проход и оптимизация
        loss.backward()
        optimizer.step()

    # Выводим значение функции потерь на каждой эпохе
    print(f'Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item()}')

# Оцениваем модель на тестовом наборе данных
with torch.no_grad():
    test_outputs = model(X_test)
    test_loss = criterion(test_outputs, y_test)
    print(f'Loss on test data: {test_loss.item()}')

/usr/local/lib/python3.10/dist-packages/torch/nn/modules/loss.py:536: UserWarning: Using a target size (torch.Size([32])) that is different to the input size (torch.Size([32, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)
/usr/local/lib/python3.10/dist-packages/torch/nn/modules/loss.py:536: UserWarning: Using a target size (torch.Size([16])) that is different to the input size (torch.Size([16, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)


Epoch [1/100], Loss: 16110.01953125
Epoch [2/100], Loss: 16113.03125
Epoch [3/100], Loss: 16115.9970703125
Epoch [4/100], Loss: 16118.8984375
Epoch [5/100], Loss: 16121.720703125
Epoch [6/100], Loss: 16124.4541015625
Epoch [7/100], Loss: 16127.095703125
Epoch [8/100], Loss: 16129.6337890625
Epoch [9/100], Loss: 16132.0703125
Epoch [10/100], Loss: 16134.404296875
Epoch [11/100], Loss: 16136.630859375
Epoch [12/100], Loss: 16138.75390625
Epoch [13/100], Loss: 16140.771484375
Epoch [14/100], Loss: 16142.6923828125
Epoch [15/100], Loss: 16144.5126953125
Epoch [16/100], Loss: 16146.23828125
Epoch [17/100], Loss: 16147.8720703125
Epoch [18/100], Loss: 16149.41796875
Epoch [19/100], Loss: 16150.8779296875
Epoch [20/100], Loss: 16152.259765625
Epoch [21/100], Loss: 16153.5615234375
Epoch [22/100], Loss: 16154.7900390625
Epoch [23/100], Loss: 16155.9482421875
Epoch [24/100], Loss: 16157.0390625
Epoch [25/100], Loss: 16158.0673828125
Epoch [26/100], Loss: 16159.037109375
Epoch [27/100], Loss: 16

/usr/local/lib/python3.10/dist-packages/torch/nn/modules/loss.py:536: UserWarning: Using a target size (torch.Size([20])) that is different to the input size (torch.Size([20, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)


2.4.3.1 Модифицируйте класс `Linear` из __2.1.4__. ([вычисление градиентов](https://i.ibb.co/kgVR6m6/photo-2021-02-15-21-30-28.jpg))

In [ ]:
class Linear:
    def __init__(self, n_features, n_neurons):
        self.weights = torch.randn(n_features, n_neurons)
        self.biases = torch.zeros(1, n_neurons)  # Создание тензора для смещений

    def forward(self, inputs):
        self.inputs = inputs
        self.output = torch.matmul(inputs, self.weights) + self.biases
        return self.output

    def backward(self, dvalues):
        # Градиент по весам, смещениям и входам
        self.dweights = torch.matmul(self.inputs.T, dvalues)
        self.dbiases = torch.sum(dvalues, axis=0, keepdim=True)
        self.dinputs = torch.matmul(dvalues, self.weights.T)
        return self.dinputs, self.dweights, self.dbiases




2.4.4 Используя наработки из 2.4, создайте нейросеть и решите задачу регрессии.

Предлагаемая архитектура:
1. Полносвязный слой с 10 нейронами
2. Активация ReLU
3. Полносвязный слой с 1 нейроном

In [ ]:
X = torch.linspace(-1, 1, 100).view(-1, 1)
y = X.pow(2) + 0.2 * torch.rand(X.size())

In [ ]:
class Activation_ReLU:
  def forward(self, inputs):
    self.inputs = inputs
    self.output = inputs.clip(min=0)
    return self.output

  def backward(self, dvalues):
    self.dinputs = dvalues.clone()
    self.dinputs[self.inputs <= 0] = 0

In [ ]:
# создание компонентов сети
# fc1 =
# relu1 =
# fc2 =

loss = MSELoss()
lr = 0.02

ys = []
for epoch in range(2001):
  # <forward pass>
  # fc1 > relu1 > fc2 > loss

  data_loss = # <прогон через функцию потерь>

  if epoch % 200 == 0:
    print(f'epoch {epoch} mean loss {data_loss}')
    ys.append(out)

  # <backprop>
  # loss > fc2 > relu1 > fc1

  # <шаг оптимизации для fc1>

  # <шаг оптимизации для fc2>


In [ ]:
import matplotlib.pyplot as plt

fig, axs = plt.subplots(len(ys), 1, figsize=(10, 40))
for ax, y_ in zip(axs, ys):
  ax.scatter(X.numpy(), y.numpy(), color = "orange")
  ax.plot(X.numpy(), y_.numpy(), 'g-', lw=3)
  ax.set_xlim(-1.05, 1.5)
  ax.set_ylim(-0.25, 1.25)